matrix:
  include:
    - language: php
      sudo: false
      php: 7.3
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install
      script:
        - vendor/bin/phpunit -c phpunit.xml --coverage-clover ./build/logs/clover.xml
        - vendor/bin/phpcs --standard=ruleset.xml
      after_success:
        - travis_retry php vendor/bin/php-coveralls
        - |
            if [ -n "$GITHUB_API_KEY" ]; then
              git clone https://github.com/martenson/disposable-email-domains.git source_data
              if ! diff -q ./list.txt ./source_data/disposable_email_blocklist.conf &>/dev/null; then
                >&2 mv ./source_data/disposable_email_blocklist.conf ./list.txt
                rm -rf ./source_data
                git init
                git add ./list.txt
                git commit -m "Updates disposable email blocklist from github.com/martenson/disposable-email-domains via automated Travis CI cron job"
                tag=$(git describe --tags | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')
                git tag -a "${tag}"
                git -c user.name='elliotjreed-travis-automated-build' -c user.email='travis-automated-build@elliotjreed.com' commit -m init
                git push -f -q https://elliotjreed:$GITHUB_API_KEY@github.com/elliotjreed/disposable-emails-filter-php master &>/dev/null
              fi
            fi

    - language: php
      sudo: false
      php: 7.2
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install
      script:
        - vendor/bin/phpunit -c phpunit.xml

    - language: php
      sudo: false
      php: 7.1
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install
      script:
        - vendor/bin/phpunit -c phpunit.xml
