matrix:
  include:
    - language: php
      sudo: true
      php: 7.4
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - pecl install ast
        - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress --ignore-platform-reqs
      script:
        - composer run-script travis
      after_success:
        - travis_retry php vendor/bin/php-coveralls
        - |
          if [ -n "$GITHUB_API_KEY" ]; then
            git clone https://github.com/disposable-email-domains/disposable-email-domains.git source_data
            if ! diff -q ./list.txt ./source_data/disposable_email_blocklist.conf &>/dev/null; then
              git init
              git config user.name 'elliotjreed-travis-automated-build'
              git config user.email 'travis-automated-build@elliotjreed.com'
              mv ./source_data/disposable_email_blocklist.conf ./list.txt
              git add ./list.txt
              git commit -m "Updates disposable email blocklist from github.com/disposable-email-domains/disposable-email-domains via automated Travis CI cron job"
              tag=$(git describe --tags | cut -f1 -d"-" | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}')
              git tag -a "${tag}" -m "Updated disposable email blocklist from github.com/disposable-email-domains/disposable-email-domains via automated Travis CI cron job"
              git push --follow-tags -q "https://elliotjreed:${GITHUB_API_KEY}@github.com/elliotjreed/disposable-emails-filter-php" HEAD:master > /dev/null 2>&1
            else
              echo "No new updates from github.com/disposable-email-domains/disposable-email-domains"
            fi
          else
            echo "GitHub API key not provided"
            exit 1
          fi
    - language: php
      sudo: true
      php: 8.0
      cache:
        directories:
          - $HOME/.composer/cache/files
      before_script:
        - composer install --no-interaction --classmap-authoritative --no-suggest --no-progress --ignore-platform-reqs
      script:
        - composer run-script phpunit
